reunhangout/accounts/urls.py
from django.conf.urls import url, include
from django.shortcuts import redirect

from accounts import views

urlpatterns = [
    url("^profile/$", views.profile, name="accounts_profile"),
    url("^settings/(?P<slug>.+)?/$", views.account_settings, name="accounts_settings"),
    url("delete/$", views.delete_account, name='accounts_delete_account'),
    # Hijack allauth routes that we use as settings panels.
    url('social/connections/$', lambda r: redirect("accounts_settings", "connections")),
    url('email/$', lambda r: redirect('accounts_settings', 'email')),
    url("email-preview", views.email_preview, name='email_preview'),
    url("mailgun$", views.mailgun_webhook),

    url("", include('allauth.urls')),
]

reunhangout/frontend/urls.py
from django.conf.urls import url

from frontend import views

urlpatterns = [
    url("^$", views.index, name="home"),
    url("^about/$", views.about, name="about"),
    url("^terms/$", views.terms, name="terms"),
    url("^privacy/$", views.privacy, name="privacy"),
    url("^h/(.*)$", views.permalinks_gone, name='permalinks_gone'),
]

reunhangout/frontend/models.py
from django.db import models

# Create your models here.
class PageComponent(models.Model):
    key = models.CharField(max_length=255, unique=True)
    title = models.CharField(max_length=255, blank=True,
            help_text='Optional page title; used when component represents a full page (e.g. terms/license)')
    html = models.TextField()

    def __str__(self):
        return self.key

reunhangout/plenaries/models.py
import re

from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now
from richtext.utils import sanitize
from reunhangout.utils import random_webrtc_id

from jsonfield import JSONField
from timezone_field import TimeZoneField
import iso8601

class Series(models.Model):
    slug = models.SlugField(help_text="Short name for URL")

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = _("Series")
        verbose_name_plural = _("Series")

def get_etherpad_default_text():
    return settings.ETHERPAD_DEFAULT_TEXT

# Create your models here.
class Plenary(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(help_text=_("Short name for URL"), unique=True)
    max_participants = models.PositiveIntegerField(default=100,
            help_text="Maximum number of connections. Set to 0 for no limit.")
    organizer = models.CharField(max_length=100, default="", blank=True)
    image = models.ImageField(upload_to="plenaries", blank=True, null=True)

    start_date  = models.DateTimeField(help_text=_("When will the event start?"))
    doors_open  = models.DateTimeField(help_text=_("When should the lobby be opened, allowing participants to chat before the event?"))
    end_date    = models.DateTimeField(help_text=_("When will the event end?"))
    doors_close = models.DateTimeField(help_text=_("When should the lobby be closed, ending chat?"))
    wrapup_emails = models.BooleanField(default=False, help_text=_(
        "Enable wrap-up emails? Enabling will require participants "
        "to set their contact preferences. Wrap-up emails can only "
        "be initiated by Unhangout staff."
    ))
    canceled = models.BooleanField(default=False)

    time_zone = TimeZoneField(default='America/New_York',
        help_text=_("Default time zone to display times in."))
    public = models.BooleanField(default=False,
        help_text=_("Check to display this plenary on the public events list"))
    description = models.TextField(default="", blank=True,)

    whiteboard = models.TextField(
        default="Welcome to our unhangout! Say hi 👋 in the chat.",
        blank=True)

    etherpad_initial_text = models.TextField(
        default=get_etherpad_default_text,
        blank=True, null=True)

    breakout_mode = models.CharField(max_length=20, choices=(
        ("admin", _("Admin controlled")),
        ("user", _("Participant proposed")),
        ("random", _("Random breakouts"))
    ), default="admin")
    random_max_attendees = models.IntegerField(default=10, validators=[
        MinValueValidator(2),
        MaxValueValidator(10),
    ])

    embeds = JSONField(blank=True, null=True)
    history = JSONField(blank=True, null=True)

    breakouts_open = models.BooleanField(default=False, help_text=_(
        "Check to allow people to join breakouts associated with this plenary"))

    webrtc_id = models.CharField(max_length=100, default=random_webrtc_id,
            editable=False, unique=True)

    live_participants = models.ManyToManyField(settings.AUTH_USER_MODEL,
            related_name='plenaries_participating_live', blank=True)
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL)
    jitsi_server = models.CharField(max_length=255, choices=(
        [(a,a) for a in settings.JITSI_SERVERS]
    ), default=settings.JITSI_SERVERS[0])

    def clean(self):
        if self.slug:
            self.slug = self.slug.lower()
        for key in ["start_date", "end_date", "doors_open", "doors_close"]:
            date = getattr(self, key)
            if isinstance(date, str):
                try:
                    setattr(self, key, iso8601.parse_date(date))
                except iso8601.ParseError:
                    raise ValidationError("%s: date format not understood" % key)
        if re.match('^[0-9]+$', self.slug) and int(self.slug) != self.id:
            raise ValidationError("Slug must contain at least one letter")
        if self.start_date >= self.end_date:
            raise ValidationError("End date must be after start date")
        if self.doors_open > self.start_date:
            raise ValidationError("Doors open must be before or equal to start date")
        if self.doors_close < self.end_date:
            raise ValidationError("Doors close must be after or equal to end date")

    def serialize(self):
        return {
            'admins': [a.serialize_public() for a in self.admins.all()],
            'breakout_mode': self.breakout_mode,
            'breakouts_open': self.breakouts_open,
            'canceled': self.canceled,
            'description': self.safe_description(),
            'doors_close': self.doors_close.isoformat(),
            'doors_open': self.doors_open.isoformat(),
            'embeds': self.embeds,
            'end_date': self.end_date.isoformat(),
            'etherpad_initial_text': self.etherpad_initial_text,
            'history': self.history,
            'id': self.id,
            'image': self.image.url if self.image else None,
            'live_participants': list(self.live_participants.values_list('id', flat=True)),
            'max_participants': self.max_participants,
            'name': self.name,
            'open': self.open,
            'organizer': self.organizer,
            'public': self.public,
            'slug': self.slug,
            'start_date': self.start_date.isoformat(),
            'time_zone': str(self.time_zone),
            'url': self.get_absolute_url(),
            'video_sync_id': self.channel_group_name,
            'webrtc_id': self.webrtc_id,
            'whiteboard': self.safe_whiteboard(),
            'wrapup_emails': self.wrapup_emails,
        }


    def associated_users(self):
        """
        Get all users associated with the plenary. We need to take care in this
        query as the performance can blow out of proportion.  This is the
        original way we tried this, which builds a stack of LEFT OUTER JOIN's
        and blew up into >40s query time:

        plenary_users = User.objects.filter(
            models.Q(plenary=self) | # admins
            models.Q(presence__room__channel_name__in=channels) |
            models.Q(mentioned_chats__plenary=self) |
            models.Q(chatmessage__plenary=self) |
            models.Q(plenaries_participating_live=self) |
            models.Q(member_of_breakouts__id__in=breakout_ids) |
            models.Q(voted_on_breakouts__id__in=breakout_ids) |
            models.Q(proposed_breakouts__id__in=breakout_ids)
        ).order_by('id').distinct('id')

        Corresponding SQL:

        => SELECT DISTINCT (...)
        -> FROM "accounts_user"
        -> LEFT OUTER JOIN "plenaries_plenary_admins"
        ->      ON ("accounts_user"."id" = "plenaries_plenary_admins"."user_id")
        -> LEFT OUTER JOIN "channels_presence_presence"
        ->      ON ("accounts_user"."id" = "channels_presence_presence"."user_id")
        -> LEFT OUTER JOIN "channels_presence_room"
        ->      ON ("channels_presence_presence"."room_id" = "channels_presence_room"."id")
        -> LEFT OUTER JOIN "plenaries_chatmessage_mentions"
        ->      ON ("accounts_user"."id" = "plenaries_chatmessage_mentions"."user_id")
        -> LEFT OUTER JOIN "plenaries_chatmessage"
        ->      ON ("plenaries_chatmessage_mentions"."chatmessage_id" =
        ->        ->"plenaries_chatmessage"."id")
        -> LEFT OUTER JOIN "plenaries_chatmessage" T9
        ->      ON ("accounts_user"."id" = T9."user_id")
        -> LEFT OUTER JOIN "plenaries_plenary_live_participants"
        ->      ON ("accounts_user"."id" = "plenaries_plenary_live_participants"."user_id")
        -> LEFT OUTER JOIN "breakouts_breakout_members"
        ->      ON ("accounts_user"."id" = "breakouts_breakout_members"."user_id")
        -> LEFT OUTER JOIN "breakouts_breakout_votes"
        ->      ON ("accounts_user"."id" = "breakouts_breakout_votes"."user_id")
        -> LEFT OUTER JOIN "breakouts_breakout" T17
        ->      ON ("accounts_user"."id" = T17."proposed_by_id")
        -> WHERE ("plenaries_plenary_admins"."plenary_id" = 1104 OR
        ->   "channels_presence_room"."channel_name" IN (
        ->       'breakout-198', 'breakout-199', 'breakout-200', 'breakout-201',
        ->       'plenary-154'
        ->   ) OR
        ->   "plenaries_chatmessage"."plenary_id" = 154 OR
        ->   T9."plenary_id" = 154 OR
        ->   "plenaries_plenary_live_participants"."plenary_id" = 154 OR
        ->   "breakouts_breakout_members"."breakout_id" IN (198, 199, 200, 201) OR
        ->   "breakouts_breakout_votes"."breakout_id" IN (198, 199, 200, 201) OR
        ->   T17."id" IN (198, 199, 200, 201))
        -> ORDER BY "accounts_user"."id" ASC;


        The present strategy is based on replacing all those joins with
        subqueries, which is WAY more efficient in postgres. This is the target
        SQL:

        => SELECT DISTINCT ON ("accounts_user"."id")
        ->   "accounts_user"."id"
        -> FROM "accounts_user"
        -> WHERE
        ->   "accounts_user"."id" IN (
        ->       SELECT "channels_presence_presence"."user_id"
        ->       FROM "channels_presence_presence"
        ->       INNER JOIN "channels_presence_room"
        ->        ->ON ("channels_presence_presence"."room_id" =
        ->        ->    "channels_presence_room"."id")
        ->       WHERE "channels_presence_room"."channel_name" IN (
        ->        ->'breakout-198', 'breakout-199', 'breakout-200',
        ->        ->'breakout-201', 'plenary-154'
        ->      )
        ->   ) OR

reunhangout/frontend/views.py
from django.shortcuts import render

from frontend.models import PageComponent

def page_component_view(request, key, default_title):
    pc, created = PageComponent.objects.get_or_create(key=key)
    if created:
        pc.title = default_title
        pc.html = '<h1>%s</h1><p>... admin, edit me ...</p>' % default_title
        pc.save()
    return render(request, "frontend/page_component_simple.html", {
        'title': pc.title,
        'key': key
    })

def index(request):
    return render(request, "frontend/index.html")

def about(request):
    return render(request, "frontend/about.html")

def terms(request):
    return page_component_view(request, "terms_page", "Terms of Service")

def privacy(request):
    return page_component_view(request, "privacy_page", "Privacy Policy")

def permalinks_gone(request, slug):
    return render(request, "frontend/permalinks_gone.html")

reunhangout/frontend/templates/_footer.html
<!--{% load thumbnail %}


<div class='container section footer'>
  {% thumbnail branding.logo_png "x40" format="PNG" as thumb %}
    <a href='/'><img src='{{ thumb.url }}' alt='{{ branding.name }}' /></a>
  {% endthumbnail %}
  <div class='links'>
    <ul>
      <li><a href='{% url 'about' %}'>About</a></li>
      <li><a href='https://github.com/unhangout/unhangout'>Source code on GitHub</a></li>
      <li><a href='{% url 'plenary_list' %}'>Upcoming events</a></li>
    </ul>
    <ul>
      <li><a href='{% url 'terms' %}'>Trems of Service</a></li>
      <li><a href='{% url 'privacy' %}'>Privacy Policy</a></li>
      <li style='list-style-type: none;'>&copy; {% now "Y" %}</li>
    </ul>
  </div>
</div>-->

reunhangout/frontend/templates/_navbar.html
{% load static %}
{% load thumbnail %}
{% load account %}

<div class='navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#navbar-ex-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      {% if not brandless %}
        <a class='navbar-brand' href='/'>
          <img src='{{ MEDIA_URL }}{{ branding.short_logo_seafoam }}' class="img-responsive" alt='{{ branding.name }}' />
        </a>
      {% endif %}
    </div>
    <div class='collapse navbar-collapse' id='navbar-ex-collapse'>
      {% if not hidenav %}
      <ul class='nav navbar-nav'>
        <li><a href='{% url "about" %}'>About</a></li>
        <li><a href='{% url "plenary_list" %}'>Events</a></li>
      </ul>
      {% endif %}
      <ul class='nav navbar-nav navbar-right'>
        {% if user.is_authenticated %}
          <li>
            <a href='{% url "accounts_settings" %}'
               class='dropdown-toggle user-name'
               data-toggle='dropdown'
               role='button'
               aria-haspopup='true'
               aria-expanded='false'>
             <img src='{{user.get_profile_image}}' class='navbar-avatar' width='32' height='32' />
            <span class='navbar-username'>{% user_display user %}<i class="fa fa-caret-down" aria-hidden="true"></i></span>
            </a>
            <ul class='dropdown-menu'>
              {% if user.is_staff %}
                <li><a href='{% url "admin:index" %}'>Admin</a></li>
                <li role='separator' class='divider'></li>
              {% endif %}
              <li>
                <a href='{% url "accounts_settings" %}'>
                  <i class='fa fa-cog'></i> Settings
                </a>
              </li>
              {% if user.plenary_set.exists %}
                <li>
                  <a href='{% url "plenary_my_events" %}'>My Events</a>
                </li>
              {% endif %}
              <li role='separator' class='divider'></li>
              <li>
                <form method='post' action='{% url "account_logout" %}'>{% csrf_token %}
                  <button type='submit' class='btn btn-link'>Logout</button>
                </form>
              </li>
            </ul>
          </li>
        {% else %}
          <li>
              <p class='navbar-btn'><a href='{% url "account_login" %}' type='button' class='btn btn-default btn-login'>Login</a></p>
          </li>
          <li>
              <p class='navbar-btn'><a href='{% url "account_signup" %}' type='button' class='btn btn-success btn-signup'>Sign up</a></p>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% block messages %}
  {% if messages %}
    <div class='messages container'>
      {% for message in messages %}
        <div role='alert'
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            class='alert alert-dismissible alert-danger'
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            class='alert alert-dismissible alert-warning'
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            class='alert alert-dismissible alert-success'
          {% else %}
            class='alert alert-dismissible alert-info'
          {% endif %}
          >{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

reunhangout/frontend/templates/base.html
{% load render_bundle from webpack_loader %}
{% load thumbnail %}
{% load static %}
{% load escapejson %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=EDGE">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block head_title %}{% endblock %}{% block title %}{% endblock %}{% block site_title %} - {{request.site.name}}{% endblock %}</title>
  {% block styles %}
    {% render_bundle 'frontend' 'css' %}
  {% endblock %}
  <script type='text/javascript'>window.__SETTINGS__ = {{public_settings|escapejson}};</script>

  {# Favicon #}
  {% with favicon="assets/unhangout-logo-UN-seafoam.png" %}
    {% thumbnail favicon "64x64" format="PNG" as thumb %}
      <link rel='icon' href='{{ thumb.url }}' />
    {% endthumbnail %}
    {% thumbnail favicon "60x60" format="PNG" as thumb %}
      <link rel='apple-touch-icon' sizes="60x60" href='{{ thumb.url }}' />
    {% endthumbnail %}
    {% thumbnail favicon "72x72" format="PNG" as thumb %}
      <link rel='apple-touch-icon' sizes="72x72" href='{{ thumb.url }}' />
    {% endthumbnail %}
    {% thumbnail favicon "120x120" format="PNG" as thumb %}
      <link rel='apple-touch-icon' sizes="120x120" href='{{ thumb.url }}' />
    {% endthumbnail %}
    {% thumbnail favicon "152x152" format="PNG" as thumb %}
      <link rel='apple-touch-icon' sizes="152x152" href='{{ thumb.url }}' />
    {% endthumbnail %}
  {% endwith %}

  {% block head %}{% endblock %}
</head>
<body>
<div id='wrapper'>
  <div id='body'>
    {% block navbar %}{% include "_navbar.html" %}{% endblock %}
    {% block main %}
      {% block content %}{% endblock %}
    {% endblock %}
  </div>
</div>
{% block scripts %}
  {% render_bundle 'frontend' 'js' %}
{% endblock %}
</body>
</html>